- hosts: gui
  become: yes

  vars_files:
    - shari_vari.yml

  tasks:

    # Not in ubuntu-studio

    - name: Install mixxx packages.
      action: apt pkg={{ item }} state=present
      with_items:
        - mixxx

    - name: check if media archive path already exists
      stat: path={{ archive_path }}/mixxx/
      register: check_archive_path

    - name: create mixxx path
      file: path={{ archive_path }}/mixxx state=directory mode=0755

    - name: move mixxx deb files
      shell: mv /var/cache/apt/archives/*.deb {{ archive_path }}/mixxx/
      when: not check_archive_path.stat.exists

    - name: Install giada packages.
      action: apt pkg={{ item }} state=present
      with_items:
        - giada

    - name: check if media archive path already exists
      stat: path={{ archive_path }}/giada/
      register: check_archive_path

    - name: create giada path
      file: path={{ archive_path }}/giada state=directory mode=0755

    - name: move giada deb files
      shell: mv /var/cache/apt/archives/*.deb {{ archive_path }}/giada/
      when: not check_archive_path.stat.exists


      
