- hosts: gui
  become: yes

  vars_files:
    - shari_vari.yml

  tasks:

    # via: https://stackoverflow.com/questions/21892603/how-to-make-ansible-execute-a-shell-script-if-a-package-is-not-installed
    - name: Check if inkscape is installed
      command: dpkg-query -l inkscape
      register: deb_check
    
    # this exists in ubuntu-studio by default
    - name: Install inkscape packages.
      action: apt pkg={{ item }} state=present
      with_items:
        - inkscape

    # this shouldn't be necessary with deb_check    
    #- name: check if media archive path already exists
    #  stat: path={{ archive_path }}/inkscape/
    #  register: check_archive_path

    - name: create inkscape path
      file: path={{ archive_path }}/inkscape state=directory mode=0755

    - name: move inkscape deb files if inkscape was not installed
      shell: mv /var/cache/apt/archives/*.deb {{ archive_path }}/inkscape/
      #when: not check_archive_path.stat.exists
      when: deb_check.stdout.find('no packages found') != -1

      
    - name: Check if blender is installed
      command: dpkg-query -l blender
      register: deb_check
      
    - name: Install blender packages.
      action: apt pkg={{ item }} state=present
      with_items:
        - blender

    - name: create blender path
      file: path={{ archive_path }}/blender state=directory mode=0755

    - name: move blender deb files
      shell: mv /var/cache/apt/archives/*.deb {{ archive_path }}/blender/
      when: deb_check.stdout.find('no packages found') != -1


      
    - name: Check if audacity is installed
      command: dpkg-query -l audacity
      register: deb_check
      
    - name: Install audacity packages.
      action: apt pkg={{ item }} state=present
      with_items:
        - audacity
        - lame

    - name: create audacity path
      file: path={{ archive_path }}/audacity state=directory mode=0755

    - name: move audacity deb files
      shell: mv /var/cache/apt/archives/*.deb {{ archive_path }}/audacity/
      when: deb_check.stdout.find('no packages found') != -1




    - name: Check if puredata is installed
      command: dpkg-query -l puredata
      register: deb_check
      
    - name: Install puredata packages.
      action: apt pkg={{ item }} state=present
      with_items:
        - puredata
        - pd-zexy
        - pd-cxc

    - name: create puredata path
      file: path={{ archive_path }}/puredata state=directory mode=0755

    - name: move puredata deb files
      shell: mv /var/cache/apt/archives/*.deb {{ archive_path }}/puredata/
      when: deb_check.stdout.find('no packages found') != -1

      
      
      
