#Install ansible on the guest OS (ahhh... the metas!)

#sudo git clone https://github.com/ansible/ansible.git /usr/local/src/ansible
#cd /usr/local/src/ansible
#sudo chown -R {{ ansible_ssh_user }}: .
#git submodule update --init --recursive
#source ./hacking/env-setup
- hosts: all
  become: yes

  vars_files:
    - shari_vari.yml
    
  vars:
    ansible_path: "/usr/local/src/ansible"

  tasks:
    # Apt package installation of required software.
    - name: Install ansible dependencies.
      action: apt pkg={{ item }} state=present
      with_items:
        # these are dependencies for ansible:
        # https://www.ansible.com/2014/02/12/installing-and-building-docker-with-ansible
        - python-yaml
        - python-jinja2
        - python-pycurl

    # this is an attempt at installing from the source...
    # but pip is usually sufficient
    - git: repo=https://github.com/ansible/ansible.git dest={{ ansible_path }}

    - shell: source ./hacking/env-setup
      args:
        chdir: {{ ansible_path }}
        executable: /bin/bash
        