#Install ansible on the guest OS (ahhh... the metas!)
- hosts: core
  become: yes

  vars_files:
    - shari_vari.yml
    
  tasks:
    # Apt package installation of required software.
    - name: Install ansible dependencies.
      action: apt pkg={{ item }} state=present
      with_items:
        - build-essential
        - libssl-dev
        - python-dev
        - libffi-dev
        #these were probably installed earlier, but just in case:
        - python-pip
        - python2.7-dev
        # no need for keys this way
        - sshpass

    #sudo pip install ansible markupsafe
    - name: pip install ansible
      pip: name=ansible

    - name: pip install markupsafe
      pip: name=markupsafe
      

        