- hosts: all
  remote_user: charles
  become: yes

  vars_files:
    - shari_vari.yml
    
  tasks:
    #this is a large installation due to the dependencies on KDE
    - name: Install k4dirstat packages.
      action: apt pkg={{ item }} state=present
      with_items:
        - k4dirstat

    - name: check if media archive path already exists
      stat: path={{ archive_path }}/k4dirstat/
      register: check_archive_path

    - name: create k4dirstat path
      file: path={{ archive_path }}/k4dirstat state=directory mode=0755

    - name: move k4dirstat deb files
      shell: mv /var/cache/apt/archives/*.deb {{ archive_path }}/k4dirstat/
      when: not check_archive_path.stat.exists

