- hosts: gui
  become: yes

  vars_files:
    - shari_vari.yml

  tasks:
      
    - name: Install emacs
      action: apt pkg={{ item }} state=present
      with_items:
        - emacs
        - emacs-goodies-el

    - name: check if emacs archive path already exists
      stat: path={{ archive_path }}/emacs/
      register: check_archive_path

    - name: create emacs path
      file: path={{ archive_path }}/emacs state=directory mode=0755

    - name: move emacs deb files
      shell: mv /var/cache/apt/archives/*.deb {{ archive_path }}/emacs/
      when: not check_archive_path.stat.exists

