- hosts: core
  become: yes

  vars_files:
    - shari_vari.yml
    
  tasks:
    - name: Install node packages.
      action: apt pkg={{ item }} state=present
      with_items:
        - nodejs
        - npm

    - name: check if node archive path already exists
      stat: path={{ archive_path }}/node/
      register: check_archive_path

    - name: create node path
      file: path={{ archive_path }}/node state=directory mode=0755

    - name: move node deb files
      shell: mv /var/cache/apt/archives/*.deb {{ archive_path }}/node/
      when: not check_archive_path.stat.exists

    - name: pip install jsbeautifier
      pip: executable=pip3 name=jsbeautifier
      
    # python2 version
    #- pip: name=jsbeautifier

    #the version of node installed by packages is woefully out of date
    #these steps are adapted from:
    #/c/technical/javascript/node.txt

    #after node is installed from debian packages, it is only available via:
    #nodejs -v

    #http://docs.ansible.com/npm_module.html

    - shell: npm cache clean -f

    #sudo npm install -g n
    - npm: name=n global=yes

    - shell: n stable

    #now node command should work as expected:
    #node -v


    #npm -v
    #sudo npm cache clean -f
    #sudo npm update npm -g
    - npm: name=npm global=yes state=latest
    #npm -v

    #sudo npm install webpack -g
    #sudo npm install webpack-dev-server -g
    - npm: name=webpack global=yes state=latest
    - npm: name=webpack-dev-server global=yes state=latest

    # for gulp:
    #sudo npm install --global gulp-cli      
    #- npm: name=gulp-cli global=yes state=latest
    # TODO:
    # if gulp, then also browserify
    
    
    #for Firefox browser extensions
    #seems like this approach has changed
    #npm install jpm --global
    #- npm: name=jpm global=yes state=latest

    
      