- hosts: all
  remote_user: charles
  become: yes

  vars_files:
    - shari_vari.yml
    
  tasks:
    - name: Install node packages.
      action: apt pkg={{ item }} state=present
      with_items:
        - nodejs
        - npm

    - name: check if node archive path already exists
      stat: path={{ archive_path }}/node/
      register: check_archive_path

    - name: create node path
      file: path={{ archive_path }}/node state=directory mode=0755

    - name: move node deb files
      shell: mv /var/cache/apt/archives/*.deb {{ archive_path }}/node/
      when: not check_archive_path.stat.exists

    - pip: name=jsbeautifier


    - name: Install couch packages.
      action: apt pkg={{ item }} state=present
      with_items:
        - couchdb

    - name: check if couch archive path already exists
      stat: path={{ archive_path }}/couch/
      register: check_archive_path

    - name: create couch path
      file: path={{ archive_path }}/couch state=directory mode=0755

    - name: move couch deb files
      shell: mv /var/cache/apt/archives/*.deb {{ archive_path }}/couch/
      when: not check_archive_path.stat.exists
      
