- hosts: all
  remote_user: charles
  become: yes

  vars_files:
    - shari_vari.yml
    
  tasks:    
    - name: Install media packages.
      action: apt pkg={{ item }} state=present
      with_items:
        - libav-tools
        - ffmpeg
        - vlc

    - name: check if media archive path already exists
      stat: path={{ archive_path }}/media/
      register: check_archive_path

    - name: create media path
      file: path={{ archive_path }}/media state=directory mode=0755

    - name: move media deb files
      shell: mv /var/cache/apt/archives/*.deb {{ archive_path }}/media/
      when: not check_archive_path.stat.exists

    
    #shouldn't hurt anything if it's already there:      
    - git: repo=https://github.com/charlesbrandt/medley  dest={{ public_path }}/medley

    - command: python setup.py develop
      args:
        chdir: "{{ public_path }}/medley"

        
#don't forget this manual step:
# Open VLC
# Tools -> Preferences
# Uncheck:
#   - Integrate video in interface
#   - Use only one instance when started from file manager

# View -> Playlist
# Close browser tree in playlist view.

