- hosts: all
  become: yes

  vars_files:
    - shari_vari.yml
    
  tasks:
    # Apt package installation of required software.
    - name: Install python packages.
      action: apt pkg={{ item }} state=present
      with_items:
        - python-pip 
        - python2.7-dev 
        - python2.7-dbg 
        - python-imaging 
        - python-nose 
        - python-mako 
        - python-pyaudio
        - git

    - name: check if python archive path already exists
      stat: path={{ archive_path }}/python/
      register: check_archive_path

    - name: create python path
      file: path={{ archive_path }}/python state=directory mode=0755

    - name: move python deb files
      shell: mv /var/cache/apt/archives/*.deb {{ archive_path }}/python/
      when: not check_archive_path.stat.exists

    - name: Upgrade pip
      pip: name=pip state=latest
  
    #- name: pip install mercurial
    #  pip: name=mercurial

    #*2015.12.19 07:46:50
    # currently a problem with mercurial 3.6+ and hg-git... downgrading:
    # http://www.eenyhelp.com/bug-804259-mercurial-git-typeerror-exchangepush-got-an-unexpected-keyword-argument-opargs-help-215860083.html

    # if previously installed, uninstall first:
    #sudo pip uninstall mercurial
    - name: pip install mercurial
      pip: name=mercurial version=3.5.2

    - name: pip install hg-git
      pip: name=hg-git
      
    #sudo easy_install selenium
    - name: pip install selenium
      pip: name=selenium
    - name: pip install cssselect
      pip: name=cssselect

    #for interacting with web APIs (e.g. discogs, etc)
    - name: pip install oauth2
      pip: name=oauth2

    - name: copy mercurial config
      # remember: this copies from the HOST to the GUEST (not within the guest)
      # TODO: consider using a local ansible template for this:
      #copy: src=/media/charles/CHARLES/charles/.hgrc dest=/home/{{ ansible_ssh_user }}/.hgrc owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }}
      #copy: src=~/.hgrc dest=/home/{{ ansible_ssh_user }}/.hgrc owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }}
      copy: src={{ shared_path }}/{{ ansible_ssh_user }}/.hgrc dest=/home/{{ ansible_ssh_user }}/.hgrc owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }}

      