- hosts: core
  become: yes

  vars_files:
    - shari_vari.yml
    
  tasks:
    # Apt package installation of required software.
    - name: Install python packages.
      action: apt pkg={{ item }} state=present
      with_items:
        - python3-pip 
        - python3-dev 
        - python3-dbg 
        - python3-pil
        - python3-pyaudio

    - name: check if python archive path already exists
      stat: path={{ archive_path }}/python/
      register: check_archive_path

    - name: create python path
      file: path={{ archive_path }}/python state=directory mode=0755

    - name: move python deb files
      shell: mv /var/cache/apt/archives/*.deb {{ archive_path }}/python/
      when: not check_archive_path.stat.exists

    - name: Upgrade pip
      pip: executable=pip3 name=pip state=latest

    # seems to be an issue with mercurial and python3 (relies on python2)
    # just going to go with system distribution for this
    #- name: pip install mercurial
    #  pip: executable=pip3 name=mercurial

    #*2015.12.19 07:46:50
    # currently a problem with mercurial 3.6+ and hg-git... downgrading:
    # http://www.eenyhelp.com/bug-804259-mercurial-git-typeerror-exchangepush-got-an-unexpected-keyword-argument-opargs-help-215860083.html

    # if previously installed, uninstall first:
    #sudo pip uninstall mercurial
    #- name: pip install mercurial
    #  pip: name=mercurial version=3.5.2

    # not using hg-git lately
    #- name: pip install hg-git
    #  pip: executable=pip3 name=hg-git

    #https://github.com/gitpython-developers/GitPython
    - name: pip install gitpython
      pip: executable=pip3 name=gitpython
      
    - name: pip install nose
      pip: executable=pip3 name=nose
    - name: pip install mako
      pip: executable=pip3 name=mako

    #sudo easy_install selenium
    - name: pip install selenium
      pip: executable=pip3 name=selenium
    #looks like this is already installed:
    - name: pip install lxml
      pip: executable=pip3 name=lxml
    - name: pip install cssselect
      pip: executable=pip3 name=cssselect

    #for interacting with web APIs (e.g. discogs, etc)
    - name: pip install oauth2
      pip: executable=pip3 name=oauth2

    #sudo pip3 install uwsgi
    - name: pip install uwsgi
      pip: executable=pip3 name=uwsgi
      
      
    - name: copy mercurial config
      # remember: this copies from the HOST to the GUEST (not within the guest)
      # TODO: consider using a local ansible template for this:
      #copy: src=/media/charles/CHARLES/charles/.hgrc dest=/home/{{ ansible_user }}/.hgrc owner={{ ansible_user }} group={{ ansible_user }}
      #copy: src=~/.hgrc dest=/home/{{ ansible_user }}/.hgrc owner={{ ansible_user }} group={{ ansible_user }}
      copy: src={{ shared_path }}/{{ ansible_user }}/.hgrc dest=/home/{{ ansible_user }}/.hgrc owner={{ ansible_user }} group={{ ansible_user }}
      #copy: src={{ shared_path }}/configs/.hgrc dest=/home/{{ ansible_user }}/.hgrc owner={{ ansible_user }} group={{ ansible_user }}

      
