- hosts: all
  become: yes

  vars_files:
    - shari_vari.yml

  vars:
    moments_path: "{{ public_path }}/moments"
    
  tasks:
    #this section previously at the end of python.yml
    
    #some of these steps may not be necessary if using a shared /c folder
    #the files could be available already...
    #in that case, the process will be different
    
    - git: repo=https://github.com/charlesbrandt/moments  dest={{ moments_path }}

    - command: python setup.py develop
      args:
        chdir: "{{ moments_path }}" 

    - file: src={{ moments_path }}/editors/vi/.exrc dest=/home/{{ ansible_ssh_user }}/.exrc owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} state=link

    - file: dest=/home/{{ ansible_ssh_user }}/.bashrc state=absent

    - file: src={{ moments_path }}/editors/.bashrc dest=/home/{{ ansible_ssh_user }}/.bashrc owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} state=link


    #previously at the end of utilities.yml (requires moments repo)

    - file: src={{ moments_path }}/editors/emacs/.emacs dest=/home/{{ ansible_ssh_user }}/.emacs owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} state=link
    - file: src={{ moments_path }}/editors/emacs/.emacs.d dest=/home/{{ ansible_ssh_user }}/.emacs.d owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} state=link

    - git: repo=https://github.com/charlesbrandt/templates.git  dest={{ public_path }}/templates
      
    - git: repo=https://github.com/charlesbrandt/mindstream  dest={{ public_path }}/mindstream

    - command: python setup.py develop
      args:
        chdir: "{{ public_path }}/mindstream"

