- hosts: core
  become: yes

  vars_files:
    - shari_vari.yml
    
  tasks:

    #had qt installation happening here...
    #may be possible that some utilities rely on qt
    #medley does, but I'm not sure what else.
    #moving it out for now

    - name: Install utilities
      action: apt pkg={{ item }} state=present
      with_items:
        # seems to be there by default now:
        #- build-essential
        - gstreamer-tools
        #- libjpeg-progs
        # missing as of 16.04... can't remember what depends on it
        #- libgif4
        - libjpeg-turbo-progs
        - jhead
        - tofrodos
        - imagemagick
        - smartmontools
        - p7zip
        - gpick
        - exfat-utils
        - exfat-fuse
        - extlinux
        - curl
        - nginx

    - name: check if utilities archive path already exists
      stat: path={{ archive_path }}/utilities/
      register: check_archive_path

    - name: create utilities path
      file: path={{ archive_path }}/utilities state=directory mode=0755

    - name: move utilities deb files
      shell: mv /var/cache/apt/archives/*.deb {{ archive_path }}/utilities/
      when: not check_archive_path.stat.exists


      
